export function buildInsumoRequestDTO(insumo) {
  return {
    grupo: insumo.grupo || "",
    subgrupo: insumo.subgrupo || "",
    nombre: insumo.nombre || "",
    pesoNeto: insumo.pesoNeto ?? 0,
    energiaKcal: insumo.energiaKcal ?? 0,
    aguaG: insumo.aguaG ?? 0,
    proteinaAnimalG: insumo.proteinaAnimalG ?? 0,
    proteinaVegetalG: insumo.proteinaVegetalG ?? 0,
    nitrogenoAnimalG: insumo.nitrogenoAnimalG ?? 0,
    nitrogenoVegetalG: insumo.nitrogenoVegetalG ?? 0,
    grasaAnimalG: insumo.grasaAnimalG ?? 0,
    grasaVegetalG: insumo.grasaVegetalG ?? 0,
    choCarbohidratoG: insumo.choCarbohidratoG ?? 0,
    fibraG: insumo.fibraG ?? 0,
    calcioAnimalMg: insumo.calcioAnimalMg ?? 0,
    calcioVegetalMg: insumo.calcioVegetalMg ?? 0,
    fosforoMg: insumo.fosforoMg ?? 0,
    hierroHemMg: insumo.hierroHemMg ?? 0,
    hierroNoHemMg: insumo.hierroNoHemMg ?? 0,
    retinolMcg: insumo.retinolMcg ?? 0,
    vitaminaB1TiaminaMg: insumo.vitaminaB1TiaminaMg ?? 0,
    vitaminaB2RiboflavinaMg: insumo.vitaminaB2RiboflavinaMg ?? 0,
    niacinaMg: insumo.niacinaMg ?? 0,
    vitaminaCMg: insumo.vitaminaCMg ?? 0,
    sodioMg: insumo.sodioMg ?? 0,
    potasioMg: insumo.potasioMg ?? 0,
    usuarioRegistro: insumo.usuarioRegistro || "",
    fechaRegistro: insumo.fechaRegistro || null,
    usuarioModificacion: insumo.usuarioModificacion || "",
    fechaModificacion: insumo.fechaModificacion || null,
    estado: insumo.estado || "ACTIVO",
  };
}
